name: Node.js CI/CD

on: 
  push:
    branches:
      - main

jobs:
  node-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Node CI/CD Started"
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Set up Yarn
      - name: Setup Yarn
        run: |
          corepack enable
          corepack prepare yarn@stable --activate

      # Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test


# name: Node js CI/CD

# on: 
#   push:
#     branches:
#       - main

# jobs:
#   node-job:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "Node CI/CD Started"
#       - name: Checkout
#         uses: actions/checkout@v3
#       - name: Run a one-line script
#         run: echo "Hello world!"
#       - name: Run a multiline script
#         run: |
#           echo Add other actions to build
#           echo test, and deploy your project
#       - name: List files
#         run: ls ${{ github.workspace }}
#       - name: Print GitHub Context
#         env: 
#           GITHUB_CONTEXT: ${{ toJson(github) }}
#         run: echo "$GITHUB_CONTEXT"
#       - name: Action Completed
#         run: echo "Action Completed"
